### ISSUE TITLE
Players get no prompts when a word is guessed correctly and when the game is moving on to the next level

### ISSUE THREAD

**Issue by ilginem** [NovaInfiniteLoops/Hangman-Team#30]
Need a prompt when a word is guessed correctly and the player is advancing to the next level

**Comment by ilginem** [comment]
This issue is addressed technically, graphically it can be improved

**Comment by novase** [comment]
Ok. Message is displayed in right margin informing of a level win, then user is given a 2000 ms pause before proceeding to next level
